- name: Load Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.durgasri.in -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data
