- name: Backend
  hosts: backend
  become: true

  vars:
    db_hoste: 172.31.40.76
    db_pass: ExpenseApp
    db_user: root

  tasks:
    - name: desable noodejs 16 module
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enable nodejs 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y
    
    - name: installing nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: Create expense user
      ansible.builtin.user:
        name: expense

    - name: creating app directory 
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: download and extract backend content 
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Install node.js Dependencies.
      community.general.npm:
        name: npm
        path: /app
    
    - name: copy backend service file 
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    
    - name: install mysql clint
      ansible.builtin.dnf:
        name:
          - mysql
          - python3-PyMySQL
        state: present

    - name: Import database schema
      community.mysql.mysql_db:
        name: all
        target: /app/schema/backend.sql
        state: import
        login_user: "{{ db_user }}"
        login_password: "{{ db_pass }}"
        login_host: "{{ db_host }}"

    - name: Start backend service
      ansible.builtin.systemd_service:
        name: backend
        enabled: true
        state: restarted
        daemon_reload: true