- name: setup nginx
  hosts: frontend
  become: yes
  tasks:
    - name: installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
        enabled: true
    
    - name: restart nginx
      ansible.builtin.service:
        state: restart
        enabled: yes