- name: setup nginx configuration
  hosts: localhost
  become: yes
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:

    - name: print msg # single fact
      debug:
        msg: "{{ ansible_facts['architecture'] }}"
        
    
    - name : print loop
      debug:
        msg: names in {{ item }}
      loop:
        - hari
        - prasad
        - chowdary
        - chandra
      when: item != "chowdary"


