- name: setup nginx configuration
  hosts: localhost
  become: yes
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:

    - name: print msg
      debug:
        msg: "{{ ansible_facts['architecture'] }}" and ansible_facts

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      when:
        - ansible_facts['os_family'] == "Debian"
  
