- name: setup nginx configuration
  hosts: localhost
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: print vars
      debug:
        msg: "{{ name }}"
    
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian"

