- name: setup nginx configration
  hots: localhost
  vars_file:
    - vars.yml
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
        when: {{os_family}} == rhel
    
    - name: print vars
      debug:
        msg: "{{name}}"