- name: nginx automation
  hosts: localhost
  become: yes
  vars:
    NAME: hari
  tasks:
#play level variable
    - name: variable from play level
      debug:
        msg: "{{ NAME }}"

#task level variable
    - name: variable from task level
      vars:
        AGE: 26
        msg: "user age is {{ AGE }}" # This is called variable interpolation or variable substitution — means one variable inside another variable using {{ }} syntax.
      debug:
        msg: "{{ msg }}"

# variable from file
#    - name: variable from file
#      vars_files:
#        - vars.yml
#      debug:
#        mag: name - {{ name }}, age - {{ age }},qualification - {{ qualification }}, medium - {{ medium }}
#
#
    - name: variable from file
      vars_files:
        - vars.yml
      debug:
        msg: "name - {{ name }}, age - {{ age }}, qualification - {{ qualification }}, medium - {{ medium }}"
