- name: setup nginx configuration
  hosts: localhost
  become: yes
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:

    - name: print msg # single fact
      debug:
        msg: "{{ ansible_facts['architecture'] }}"
        
    
    - name : print loop
      debug:
¸      loop:
        - hari
        - prasad
        - chandra
        
#    - name: install nginx
#      ansible.builtin.apt:
#        name: nginx
#        state: absent
#      when:
#        - ansible_facts['os_family'] == "Debian"
  
