#- name: variable from list example
#  hosts: localhost
#  vars:
#    users:
#      - Hari
#      - Chandra
#      - Prasad
#  tasks:
#    - name: Show first user
#      debug:
#        msg: "First user is {{ users[0] }}, Second user is {{ users[1] }}"
#
#    - name: Show all users with loop
#      debug:
#        msg: "User: {{ item }}"
#      loop: "{{ users }}"

#- name: variable from map example
#  hosts: localhost
#  vars:
#    student:
#      name: prasad
#      age: 20
#      class: 10
#  tasks:
#    - name: print variables from map
#      ansible.builtin.debug:
#        msg: "Name: {{ student.name }}, Age: {{ student.age }}, Class: {{ student.class }}"
#
#- name: variable from map list example  # looping from map object
#  hosts: localhost
#  vars:
#    students:
#      - name: prasad
#        age: 20
#        class: 10
#      - name: hari
#        age: 21
#        class: 11
#  tasks:
#    - name: print each student details
#      ansible.builtin.debug:
#        msg: "Name: {{ item.name }}, Age: {{ item.age }}, Class: {{ item.class }}"
#      loop: "{{ students }}"







- name: variable from list
  vars:
    fruits:
      - apple
      - banana
      - guvva
      - grapes
  hosts: localhost
  tasks:
    - name: variable from list
      debug:
        msg: "first fruit is in: {{fruits[0]}}, second  fruit is in:{{fruits[1] }}"
      
    - name: all fruits
      debug:
        msg: fruits names are  {{ item }}
        loop: {{ fruits }}


