- name: nginx automation
  hosts: localhost
  become: yes

  vars_files:        # <--- variable from vars files
    - vars.yml
  vars:
    NAME: hari
  tasks:
#play level variable
    - name: variable from play level
      debug:
        msg: "{{ NAME }}"

#task level variable
    - name: variable from task level
      vars:
        AGE: 26
        msg: "user age is {{ AGE }}" # This is called variable interpolation or variable substitution — means one variable inside another variable using {{ }} syntax.
      debug:
        msg: "{{ msg }}"
    
# load variables from a file or directory dynamically during a playbook
    - name: Include variables from file
      ansible.builtin.include_vars:
        file: vars.yml

    - name: variable from file
      debug:
        msg: "name - {{ name }}, age - {{ age }}, qualification - {{ qualification }}, medium - {{ medium }}"

# variable from cli
- name: variable from cli
  ansible.builtin.debug:
    msg: "i am from cli {{ MY_NAME }}"