- name: Setup frontend
  hosts: frontend
  become: true
  roles:
    - frontend

#- name: Setup mongodb
#  hosts: mongodb
#  become: true
#  roles:
#    - mongodb
#
#- name: Setup Catalogue
#  hosts: catalogue
#  become: true
#  roles:
#    - catalogue

#- name: Setup Catalogue
#  hosts: redis
#  become: true
#  roles:
#    - redis

#- name: Setup Catalogue
#  hosts: user
#  become: true
#  roles:
#    - user
- name: Setup Catalogue
  hosts: cart
  become: true
  roles:
    - cart

- name: Setup Catalogue
  hosts: mysql
  become: true
  roles:
    - mysql