- name: installing ansible
  hosts: workstation
  become: true
  tasks:
    - name: remove Ansible
      ansible.builtin.dnf:
        name: ansible
        state: absent 
    
    - name: install Ansible
      ansible.builtin.dnf:
        name: ansible
        state: present