- name: install nginx
  ansible.builtin.dnf:
   name: nginx
   state: latest

#- name: start nginx service
#  ansible.builtin.service:
#   name: nginx
#   state: started
#   enable: yes
#
- name: remove old nginx content
  ansible.builtin.file:
   path: /usr/share/nginx/html/*
   state: absent
   
- name: download frontend content
  ansible.builtin.unarchive:
   src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
   dest: /usr/share/nginx/html/
   remote_src: true

- name: start nginx service
  ansible.builtin.service:
   name: nginx
   state: restarted
   enable: yes
