- name: variables from running commands
  hosts: localhost
  
  become: true
  
  tasks:
    - name: ip of the manage nodes
      ansible.builtin.debug:
        msg: "{{ ansible_all_ipv4_addresses }}"
      register: ip
    
    - name: Print the output
      ansible.builtin.debug:
        msg: "{{ ip.msg }}"
    
# in shell we call as exit status 
# in ansible we call return code 
    # [ root@workstation ]#    ;  hostname ip-172-31-35-13.ec2.internal

    - name: Run hostname command
      ansible.builtin.command: hostname
      register: result

    - name: Print return code
      ansible.builtin.debug:
        msg: "{{ result.rc }}"