- name: disable mysql
  ansible.builtin.shell: dnf module disable mysql -y

- name: copy mysql repo
  ansible.builtin.template:
   src: mysql.repo
   dest: /etc/yum.repos.d/mysql.repo
   
   
#- name: install mysql
#  ansible.builtin.dnf:
#   name: mysql
#   state: latest