- name: set hostname
  ansible.builtin.shell: set-prompt {{ component }}


- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Set Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1