- name: install mysql
  ansible.builtin.dnf:
   name: mysql
   state: latest
   
- name: Installing MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Set Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
  ignore_errors: yes