#- name: installing mysql
#  ansible.builtin.dnf:
#   name: "{{ item.name }}"
#   state: "{{ item.state }}"
#  loop:
#   - { name: 'mysql', state: 'latest' }

- name: installing mysql
  ansible.builtin.dnf:
   name: mysql
   state: latest

- name: Enable and start MySQL server
  ansible.builtin.service:
   name: mysqld
   state: started
   enabled: yes
