- name: install mysql
  ansible.builtin.dnf:
   name: mysql
   state: latest

- name: Start mysql service
  ansible.builtin.service:
   name: mysqld
   state: started
   enabled: yes

- name: install python dependencies
  ansible.builtin.pip:
   name: pymysql
   executable: pip3.9
   
- name: chick db connection
  community.mysql.mysql_info:
   login_user: root
   login_password: ExpenseApp@1
   login_host: mysql.chowdary.cloud
   filter: version
  ignore_errors: true
  register: mysql_output

- name: print output
  ansible.builtin.debug:
   msg: "output {{mysql_output}}"