- name: Disable default Nodejs and enable nodejs 20
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed


######## app-prereq
- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: Remove app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download catalogue content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /app
    remort_src: true
######## ---

- name: Install NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

######## systemd services
- name: copy catalogue service file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: start catalogue service file
  ansible.builtin.systemd:
    name: catalogue
    daemon_reload: true
    enabled: true
    state: restarted

######## ---
