- name: Run tasks/nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name : copy mongodb repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo


- name: install mongodb
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed


- name: load schema
  ansible.builtin.shell: mongosh --host {{ lookup('aws_ssm', '{{ env }}.catalogue.mongo_host', region='us-east-1' ) }} </app/db/master-data.js

