---
- name: Error handling
  hosts: localhost
  become: true

  tasks:
    - name: Handle an error
      ansible.builtin.command: pig
      register: output
      ignore_errors: true

    - name: Print the output
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - "RC: {{ output.rc }}"
        - "STDOUT: {{ output.stdout }}"
        - "STDERR: {{ output.stderr }}"