[frontend]
frontend-dev.wavedevops.online

[backend]
frontend-dev.wavedevops.online

[db]
frontend-dev.wavedevops.online
 

[all:vars]
ansible_python_interpreter=/usr/bin/python3.11
ansible_user=ec2-user
ansible_password=DevOps321
env=dev
