- name: sample
  hosts: localhost
  tasks:
    - name: vars key and values (plain)
      ansible.builtin.debug:
        msg: student name in class 1st student is  {{ STUDENT1 }}, 2nd student {{ STUDENT2 }}
      vars: 
        STUDENT1: john
        STUDENT2: ramu

    - name: key and  key  values ( list)
      ansible.builtin.debug:
        msg: student name is {{ student_info["name"][0] }}  #, student class is {{ class }}, student cource {{ cource }}
      vars:
        student_info:
          name:
            - hari
            - babu
          class: 10
          cource: aws