- name: List of maps example
  hosts: localhost
  gather_facts: false

  vars:
    students:
      - name: Hari
        class: 10
        course: AWS

      - name: Babu
        class: 9
        course: Azure

      - name: Raju
        class: 8
        course: GCP

  tasks:
    - name: Print first student
      ansible.builtin.debug:
        msg: "{{ students[0] }}"

    - name: Print first student name
      ansible.builtin.debug:
        msg: "{{ students[0].name }}"

    - name: Print second student course
      ansible.builtin.debug:
        msg: "{{ students[1].course }}"

    - name: print all students 
      ansible.builtin.debug:
        msg: students names are {{ item }}
      loop:
        - prasad
        - Hari
        - dev
        - alex
