# - name: expense app playbook
#   hosts: localhost
#   become: true
#   # tasks:  # if we use tasks, we use tasks 
#   roles:    # if we use roles, use roles
#     - frontend
#     - db
#     - backend

- name: frontend
  hosts: frontend
  become: true
  roles:
    - frontend

- name: db
  hosts: db
  become: true
  roles:
    - backend

- name: backend
  hosts: backend
  become: true
  roles:
    - backend