- name: set hostname
  ansible.builtin.shell: set-prompt {{ component }}

- name: Install nodejs
  ansible.builtin.dnf:
    name: golang
    state: installed


- name: import task app-prereq
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install {{ component }} Dependencies
  ansible.builtin.shell: go mod init dispatch ;go get ;go build
  args:
    chdir: /app

- name: import task systemd
  ansible.builtin.import_tasks:
    file: systemd.yml
