- name: set hostname
  ansible.builtin.shell: set-prompt {{ component }}

- name: Install {{ component }}
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: import task app-prereq
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install {{ component }} Dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app

- name: import task systemd
  ansible.builtin.import_tasks:
    file: systemd.yml
